FROM composer:latest AS vendor

WORKDIR /var/www/html
COPY composer* ./
RUN composer install \
  --no-interaction \
  --prefer-dist \
  --ignore-platform-reqs \
  --optimize-autoloader \
  --apcu-autoloader \
  --ansi \
  --no-scripts

FROM php:8.1-fpm-alpine

RUN set -ex \
    && apk --no-cache add postgresql-dev nodejs yarn\
    && docker-php-ext-install pdo pdo_pgsql

RUN apk add --no-cache pcre-dev $PHPIZE_DEPS \
        && pecl install redis \
        && docker-php-ext-enable redis.so

RUN curl -sS https://getcomposer.org/installer | php -- --instal-dir=/usr/local/bin --filename=composer

COPY . .
COPY --from=vendor /var/www/html/vendor vendor